p8105\_hw1\_yl4604
================
Yu Liu

This is my solution to HW1

``` r
library(tidyverse)
```

    ## -- Attaching packages ------------------------------------------------------------------------------- tidyverse 1.3.0 --

    ## v ggplot2 3.3.2     v purrr   0.3.4
    ## v tibble  3.0.1     v dplyr   1.0.0
    ## v tidyr   1.1.0     v stringr 1.4.0
    ## v readr   1.3.1     v forcats 0.5.0

    ## -- Conflicts ---------------------------------------------------------------------------------- tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(ggplot2)
```

Problem 1
---------

Create a data frame with specified elements

``` r
prob1_df = tibble(
  samp = rnorm(10),
  samp_gt_0 = samp > 0,
  char_vec = c('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'),
  factor_vec = factor(c('low', 'high', 'low', 'median', 'low', 'low', 'high', 'high', 'low', 'high'))
)
```

Take the element mean of each variables in my dataframe

``` r
mean(pull(prob1_df, samp))
mean(as.numeric(pull(prob1_df, samp_gt_0)))
mean(as.numeric(pull(prob1_df, char_gt_0)))
mean(as.numeriC(pull(prob1_df, factor_vec)))
```

I can take means of numeric and logical but not character or factor

``` r
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ##  [1] 0.5590004 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.6160831
    ##  [8] 0.0000000 0.0000000 0.3562806

``` r
as.factor(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ## Warning in Ops.factor(as.factor(pull(prob1_df, samp_gt_0)), pull(prob1_df, : '*'
    ## not meaningful for factors

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(as.factor(pull(prob1_df, samp_gt_0))) * pull(prob1_df, samp)
```

    ##  [1]  1.1180008 -0.9025301 -1.2646343 -0.9263829 -0.2368662 -0.1478099
    ##  [7]  1.2321662 -0.5311560 -0.4492225  0.7125611

problem 2
---------

``` r
data('penguins', package = 'palmerpenguins')
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

The variable names in the dataset 'penguins' are: ' species, island, bill\_length\_mm, bill\_depth\_mm, flipper\_length\_mm, body\_mass\_g, sex, year '.
There are Adelie, Gentoo, Chinstrap species in the dataset, on Torgersen, Biscoe, Dream island. There are total The range of penguins bill length is (32.1, 59.6 )mm, minimum length is 32.1mm, maximum length is 59.6mm, average length is 43.9219298mm.
The range of bill depth is (13.1, 21.5) mm, minimum depth is 13.1mm, maximum depth is 21.5mm, average depth is 17.1511696mm.
The range of flipper length is ( 172, 231) mm, minimum length is 172mm, maximum length is 231mm, average length is 200.9152047mm.
The range of body mass is (2700, 6300 )g. minimum mass is 2700mm, maximum mas is 6300mm, average mass is 4201.754386mm.

The total female is \`\#

The size of the dataset penguins is 344 \* 8 .

The mean filpper length is 200.9152047mm.

``` r
ggplot(penguins, 
       aes(x = bill_length_mm, 
           y = flipper_length_mm, 
           colour = species) )+ geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_yl4604_files/figure-markdown_github/scatterplot-1.png)

``` r
ggsave
```

    ## function (filename, plot = last_plot(), device = NULL, path = NULL, 
    ##     scale = 1, width = NA, height = NA, units = c("in", "cm", 
    ##         "mm"), dpi = 300, limitsize = TRUE, ...) 
    ## {
    ##     dpi <- parse_dpi(dpi)
    ##     dev <- plot_dev(device, filename, dpi = dpi)
    ##     dim <- plot_dim(c(width, height), scale = scale, units = units, 
    ##         limitsize = limitsize)
    ##     if (!is.null(path)) {
    ##         filename <- file.path(path, filename)
    ##     }
    ##     old_dev <- grDevices::dev.cur()
    ##     dev(filename = filename, width = dim[1], height = dim[2], 
    ##         ...)
    ##     on.exit(utils::capture.output({
    ##         grDevices::dev.off()
    ##         if (old_dev > 1) grDevices::dev.set(old_dev)
    ##     }))
    ##     grid.draw(plot)
    ##     invisible()
    ## }
    ## <bytecode: 0x000000001bce8b68>
    ## <environment: namespace:ggplot2>
